### PR TITLE
Add alpine3.15 and ubuntu 20.4 ossl3

### PR DESCRIPTION
**Pull request by JuergenReppSIT**
* Add alpine 3.15 image.
* Add ubuntu20.04 image with openssl3.

Signed-off-by: Juergen Repp <juergen.repp@sit.fraunhofer.de>

### CODE REVIEW

**Comment by williamcroberts** [comment]
Please rebase ontop of: https://github.com/tpm2-software/tpm2-software-container/pull/64

**Comment by JuergenReppSIT** [comment]
> Please rebase ontop of: #64

@williamcroberts sorry I don't know how to do it right now?

**Comment by williamcroberts** [comment]
> > Please rebase ontop of: #64
> 
> @williamcroberts sorry I don't know how to do it right now?

```bash
git checkout add-alpine3.15-and-ubuntu-20.4-ossl3
git pull --rebase origin master
```

**Comment by JuergenReppSIT** [comment]
> ```shell
> git checkout add-alpine3.15-and-ubuntu-20.4-ossl3
> git pull --rebase origin master
> ```
@williamcroberts oh sorry I was confused about "on top of #64". I did not made any changes in publish.yml. Should we add alpine to this file?

**Comment by williamcroberts** [comment]
> > ```shell
> > git checkout add-alpine3.15-and-ubuntu-20.4-ossl3
> > git pull --rebase origin master
> > ```
> 
> @williamcroberts oh sorry I was confused about "on top of #64". I did not made any changes in publish.yml. Should we add alpine to this file?

This looks good to me, I would just add them to publish and we can start pulling them into our CI.

**Comment by JuergenReppSIT** [comment]
> This looks good to me, I would just add them to publish and we can start pulling them into our CI.

@williamcroberts Can I add both  "alpine-3.15" and "ubuntu-20.04-ossl3" or should I only add "alpine-3.15" to publish?

**Comment by williamcroberts** [comment]
@JuergenReppSIT I would add them both, it doesn't hurt and we can always yank something later. I would like both images to star playing around with ensuring our tests are running on a version ossl3 across our projects.

**Comment by JuergenReppSIT** [comment]
> I would like both images to star playing around with ensuring our tests are running on a version ossl3 across our projects.

@williamcroberts  I have added both to the publish file. Is there anything else todo?

**Comment by williamcroberts** [comment]
> > I would like both images to star playing around with ensuring our tests are running on a version ossl3 across our projects.
> 
> @williamcroberts I have added both to the publish file. Is there anything else todo?

Just for me to click merge, and then they will get published to the GitHub container registry and we can start using them... clicking merge now, Thanks Juergen

**Pull request merged**
